include("${CMAKE_CURRENT_LIST_DIR}/QualityGates.cmake")

function(package_check_source_ownership)
    _lmmc_quality_collect_targets("${CMAKE_SOURCE_DIR}" _targets)
    set(_entries "")
    foreach(_target IN LISTS _targets)
        get_target_property(_type "${_target}" TYPE)
        if(_type STREQUAL "UTILITY" OR _type STREQUAL "INTERFACE_LIBRARY")
            continue()
        endif()
        get_target_property(_sources "${_target}" SOURCES)
        get_target_property(_source_dir "${_target}" SOURCE_DIR)
        foreach(_source IN LISTS _sources)
            if(_source MATCHES "^\\$<TARGET_OBJECTS:[^>]+>$")
                continue()
            endif()
            if(_source MATCHES "\\$<")
                message(FATAL_ERROR "Consumer ownership requires explicit sources: ${_target}: ${_source}")
            endif()
            cmake_path(ABSOLUTE_PATH _source BASE_DIRECTORY "${_source_dir}" NORMALIZE)
            cmake_path(IS_PREFIX CMAKE_SOURCE_DIR "${_source}" NORMALIZE _in_source)
            cmake_path(IS_PREFIX CMAKE_BINARY_DIR "${_source}" NORMALIZE _in_build)
            string(TOLOWER "${_source}" _lower_source)
            if(NOT _in_source OR _in_build OR NOT _lower_source MATCHES "\\.(c|cc|cpp|cxx)$")
                continue()
            endif()
            get_source_file_property(_header_only "${_source}"
                TARGET_DIRECTORY "${_target}" HEADER_FILE_ONLY)
            if(_header_only)
                continue()
            endif()
            _lmmc_quality_json_string("${_source}" _path)
            _lmmc_quality_json_string("${_target}" _owner)
            list(APPEND _entries "{\"path\":${_path},\"owner\":${_owner}}")
        endforeach()
    endforeach()
    list(JOIN _entries ",\n" _sources)
    file(WRITE "${CMAKE_BINARY_DIR}/source_ownership.json" "{\"sources\":[${_sources}]}\n")
endfunction()

cmake_language(DEFER DIRECTORY "${CMAKE_SOURCE_DIR}" CALL package_check_source_ownership)

# 消费者从唯一安装前缀与导出目标继承路径和语言标准，避免本地设置掩盖导出缺失。
list(LENGTH CMAKE_PREFIX_PATH _package_prefix_count)
if(NOT _package_prefix_count EQUAL 1)
    message(FATAL_ERROR "Package checks require exactly one installed CMAKE_PREFIX_PATH")
endif()
file(REAL_PATH "${CMAKE_PREFIX_PATH}" _package_check_prefix)
if(NOT IS_DIRECTORY "${_package_check_prefix}")
    message(FATAL_ERROR "Installed package prefix does not exist: ${_package_check_prefix}")
endif()
foreach(_language IN ITEMS C CXX)
    if(DEFINED CMAKE_${_language}_STANDARD)
        message(FATAL_ERROR "Package checks must inherit ${_language} standards from exported targets")
    endif()
endforeach()

function(package_check_installed_path path)
    if(NOT IS_ABSOLUTE "${path}" OR NOT EXISTS "${path}")
        message(FATAL_ERROR "Installed target exposes a missing or non-absolute path: ${path}")
    endif()
    file(REAL_PATH "${path}" _real_path)
    cmake_path(IS_PREFIX _package_check_prefix "${_real_path}" NORMALIZE _inside_prefix)
    if(NOT _inside_prefix)
        message(FATAL_ERROR "Installed target escapes the package prefix: ${path}")
    endif()
endfunction()

function(package_check_target target feature)
    if(NOT TARGET "${target}")
        message(FATAL_ERROR "Installed target is missing: ${target}")
    endif()
    get_target_property(_imported "${target}" IMPORTED)
    if(NOT _imported)
        message(FATAL_ERROR "Package consumer must link an imported target: ${target}")
    endif()
    if(NOT "${feature}" STREQUAL "")
        get_target_property(_features "${target}" INTERFACE_COMPILE_FEATURES)
        if(NOT "${feature}" IN_LIST _features)
            message(FATAL_ERROR "${target} does not export ${feature}")
        endif()
    endif()
    foreach(_property IN ITEMS INTERFACE_INCLUDE_DIRECTORIES INTERFACE_SYSTEM_INCLUDE_DIRECTORIES)
        get_target_property(_paths "${target}" "${_property}")
        if(_paths)
            foreach(_path IN LISTS _paths)
                package_check_installed_path("${_path}")
            endforeach()
        endif()
    endforeach()
    get_target_property(_configurations "${target}" IMPORTED_CONFIGURATIONS)
    set(_location_properties IMPORTED_LOCATION IMPORTED_IMPLIB)
    foreach(_configuration IN LISTS _configurations)
        list(APPEND _location_properties
            "IMPORTED_LOCATION_${_configuration}" "IMPORTED_IMPLIB_${_configuration}")
    endforeach()
    foreach(_property IN LISTS _location_properties)
        get_target_property(_location "${target}" "${_property}")
        if(_location)
            package_check_installed_path("${_location}")
        endif()
    endforeach()
    get_target_property(_dependencies "${target}" INTERFACE_LINK_LIBRARIES)
    foreach(_dependency IN LISTS _dependencies)
        get_filename_component(_dependency_name "${_dependency}" NAME)
        string(TOLOWER "${_dependency_name}" _dependency_name)
        if(_dependency_name MATCHES "(gtest|gmock|rapidcheck|cmocka)")
            message(FATAL_ERROR
                "${target} exports a development-only test dependency: ${_dependency}")
        endif()
        if(IS_ABSOLUTE "${_dependency}")
            package_check_installed_path("${_dependency}")
        endif()
    endforeach()
endfunction()

function(package_check_headers dependency include_root pattern)
    file(GLOB_RECURSE _headers CONFIGURE_DEPENDS RELATIVE "${include_root}"
        "${include_root}/${pattern}")
    if(NOT _headers)
        message(FATAL_ERROR "No public headers found for ${dependency}: ${pattern}")
    endif()
    foreach(_language IN LISTS ARGN)
        if(_language STREQUAL "C")
            set(_extension c)
        else()
            set(_extension cpp)
        endif()
        set(_sources "")
        foreach(_header IN LISTS _headers)
            string(MAKE_C_IDENTIFIER "${_language}_${_header}" _id)
            set(_source "${CMAKE_CURRENT_BINARY_DIR}/standalone_${_id}.${_extension}")
            file(CONFIGURE OUTPUT "${_source}" CONTENT "#include <${_header}>\n#ifdef LMCAS_INTERNAL_AST_INCLUDED\n#error Public headers must not include private AST implementations\n#endif\ntypedef int package_header_anchor_${_id};\n" @ONLY)
            list(APPEND _sources "${_source}")
        endforeach()
        string(MAKE_C_IDENTIFIER "${dependency}_${_language}" _target)
        add_library("standalone_${_target}" OBJECT ${_sources})
        set_target_properties("standalone_${_target}" PROPERTIES UNITY_BUILD OFF)
        target_link_libraries("standalone_${_target}" PRIVATE "${dependency}")
    endforeach()
endfunction()

function(package_check_report executable)
    string(JSON _report SET "{}" executable "\"$<TARGET_FILE:${executable}>\"")
    string(JSON _report SET "${_report}" targets "{}")
    foreach(_target IN LISTS ARGN)
        get_target_property(_type "${_target}" TYPE)
        string(JSON _record SET "{}" type "\"${_type}\"")
        string(JSON _record SET "${_record}" file "\"$<TARGET_FILE:${_target}>\"")
        string(JSON _report SET "${_report}" targets "${_target}" "${_record}")
    endforeach()
    file(GENERATE OUTPUT "${CMAKE_CURRENT_BINARY_DIR}/package_check_$<CONFIG>.json"
        CONTENT "${_report}\n")
endfunction()
